name: med_meet_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  file_picker: ^8.3.1
  shared_preferences: ^2.5.1
  socket_io_client: ^3.0.2
  logger: ^2.5.0
  flutter_rating: ^2.0.2
  table_calendar: ^3.2.0
  intl: ^0.20.2
  pinput: ^5.0.1 
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.27
  http: ^1.3.0
  http_parser: ^4.1.2
  loader_overlay: ^5.0.0  
  flutter_typeahead: ^5.2.0
  pdf: ^3.11.3 
  path_provider: ^2.1.5
  flutter_pdfview: ^1.2.9
  # easy_pdf_viewer: ^1.0.8
  dio: ^5.8.0+1
  zego_uikit_prebuilt_call: ^4.16.24
  syncfusion_flutter_pdfviewer: ^28.2.9
  zego_uikit_signaling_plugin: ^2.8.11
  firebase_core: ^3.12.1
  cached_network_image: ^3.4.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  grouped_list: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
     - assets/
     - assets/images/
     - assets/svg/
     - assets/language/
